In [1]:
import pandas as pd

Читаем файл и пропускаем строки с индексами 2,3, а также две последние строки файла, используем пайтон-движок для skipfooter, первую колонку используем как индекс

In [3]:
df = pd.read_csv('../data/feed-views.log', skiprows=[2,3], skipfooter=2, engine='python', header=None, names=['datetime', 'user'], sep='\t', index_col=0)

меняем название индексной колонки

In [5]:
df.index.name = 'date_time'

In [6]:
df.to_csv('../data/feed-views-semicolon.log', sep=';', header=False)

проверяем:

In [8]:
df.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [9]:
df.tail()

                                 user
date_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel